# Generated by Django 4.0.3 on 2022-03-28 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payment_method', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=255)),
                ('cardholders_name', models.CharField(max_length=255)),
                ('card_expiring_date', models.CharField(max_length=255)),
                ('cvv', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_infos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
